# restart 策略可选值：
#   no              - 不自动重启（默认）
#   always          - 总是自动重启
#   on-failure[:N]  - 失败时自动重启，最多N次
#   unless-stopped  - 除非手动停止，否则总是重启
services:
  # mysql配置
  mysql:
    image: mysql:8.4.2 # 镜像
    container_name: dms-data-mysql-container # 容器名称
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=kanban_data
    command: [
        '--bind-address=0.0.0.0', # 绑定地址
        '--character-set-server=utf8mb4', # 字符集
        '--collation-server=utf8mb4_unicode_ci', # 排序规则
        '--max_allowed_packet=128M', # 最大允许包
        '--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION', # sql模式
        '--default-time-zone=+8:00' # 时区
      ]
    # env_file:
    #   - ./env/.env.prod # 替换变量，注释掉的
    ports:
      - '3311:3306' # 端口
    volumes:
      - mysql-data:/var/lib/mysql # 挂载卷
    networks:
      - dms-service-data-network
    restart: on-failure:5
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p123456'] # 健康检查
      timeout: 20s # 超时
      retries: 10 # 重试次数
      interval: 5s # 间隔
      start_period: 30s # 启动时间

networks:
  dms-service-data-network:
    driver: bridge

volumes:
  mysql-data:
    name: dms-service-data-mysql-data
    driver: local
# docker-compose -p dms-data-service -f dms-service-data-compose.yml up -d --remove-orphans
# 停止 service-data 项目的容器
# docker-compose -p dms-data-service -f dms-service-data-compose.yml down
