-- Dashboard module schema.
-- Apply this script to the data_middle_station database before using /dashboard.

CREATE TABLE IF NOT EXISTS `dashboard` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `dashboard_name` varchar(255) NOT NULL COMMENT '看板名称',
  `dashboard_desc` varchar(500) DEFAULT NULL COMMENT '看板描述',
  `layout_config` json DEFAULT NULL COMMENT '看板布局配置',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_dashboard_name` (`dashboard_name`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_update_time` (`update_time`),
  KEY `idx_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='看板信息表';

CREATE TABLE IF NOT EXISTS `dashboard_widget` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `dashboard_id` bigint unsigned NOT NULL COMMENT '看板ID',
  `analyze_id` bigint unsigned NOT NULL COMMENT '分析ID',
  `widget_title` varchar(255) NOT NULL COMMENT '组件标题',
  `x` int NOT NULL DEFAULT '0' COMMENT '网格横向位置',
  `y` int NOT NULL DEFAULT '0' COMMENT '网格纵向位置',
  `w` int NOT NULL DEFAULT '4' COMMENT '网格宽度',
  `h` int NOT NULL DEFAULT '3' COMMENT '网格高度',
  `chart_type` varchar(50) NOT NULL DEFAULT 'table' COMMENT '图表类型',
  `refresh_interval` int NOT NULL DEFAULT '0' COMMENT '刷新间隔，单位秒，0 表示不自动刷新',
  `widget_config` json DEFAULT NULL COMMENT '组件局部配置',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_dashboard_id` (`dashboard_id`),
  KEY `idx_analyze_id` (`analyze_id`),
  KEY `idx_dashboard_position` (`dashboard_id`, `y`, `x`),
  CONSTRAINT `fk_dashboard_widget_dashboard` FOREIGN KEY (`dashboard_id`) REFERENCES `dashboard` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='看板组件表';

CREATE TABLE IF NOT EXISTS `resource_role_permission` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `resource_type` varchar(50) NOT NULL COMMENT '资源类型：analyze/dashboard/datasource/folder/scheduled_email',
  `resource_id` bigint unsigned NOT NULL COMMENT '资源ID',
  `role_id` bigint unsigned NOT NULL COMMENT '角色ID',
  `permission_type` varchar(20) NOT NULL DEFAULT 'view' COMMENT '权限类型：view/edit/manage',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_resource_role_permission` (`resource_type`, `resource_id`, `role_id`),
  KEY `idx_resource` (`resource_type`, `resource_id`),
  KEY `idx_role_id` (`role_id`),
  KEY `idx_permission_type` (`permission_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通用资源角色权限表';

-- Demo data. These widgets reference the sample analyze records from sql/data_middle_station.sql.
INSERT INTO `dashboard` (
  `id`,
  `dashboard_name`,
  `dashboard_desc`,
  `layout_config`,
  `create_time`,
  `created_by`,
  `update_time`,
  `updated_by`,
  `is_deleted`
) VALUES (
  1,
  '经营数据总览看板',
  '示例看板：组合销售、降雨、气温和用户渠道分析，用于验证拖拽布局、宽高调整和多分析渲染。',
  JSON_OBJECT('columnCount', 24, 'rowHeight', 60),
  NOW(),
  'admin',
  NOW(),
  'admin',
  0
) ON DUPLICATE KEY UPDATE
  `dashboard_name` = VALUES(`dashboard_name`),
  `dashboard_desc` = VALUES(`dashboard_desc`),
  `layout_config` = VALUES(`layout_config`),
  `updated_by` = VALUES(`updated_by`),
  `update_time` = NOW(),
  `is_deleted` = 0;

INSERT INTO `dashboard_widget` (
  `id`,
  `dashboard_id`,
  `analyze_id`,
  `widget_title`,
  `x`,
  `y`,
  `w`,
  `h`,
  `chart_type`,
  `refresh_interval`,
  `widget_config`,
  `create_time`,
  `created_by`,
  `update_time`,
  `updated_by`,
  `is_deleted`
) VALUES
  (
    1,
    1,
    1,
    '销售数据看板',
    0,
    0,
    6,
    3,
    'interval',
    0,
    JSON_OBJECT('showHeader', true),
    NOW(),
    'admin',
    NOW(),
    'admin',
    0
  ),
  (
    2,
    1,
    2,
    '城市-月份-降雨量',
    6,
    0,
    6,
    3,
    'interval',
    0,
    JSON_OBJECT('showHeader', true),
    NOW(),
    'admin',
    NOW(),
    'admin',
    0
  ),
  (
    3,
    1,
    3,
    '城市-月份-气温',
    0,
    3,
    6,
    3,
    'line',
    0,
    JSON_OBJECT('showHeader', true),
    NOW(),
    'admin',
    NOW(),
    'admin',
    0
  ),
  (
    4,
    1,
    4,
    '用户注册渠道分析',
    6,
    3,
    6,
    3,
    'pie',
    0,
    JSON_OBJECT('showHeader', true),
    NOW(),
    'admin',
    NOW(),
    'admin',
    0
  )
ON DUPLICATE KEY UPDATE
  `dashboard_id` = VALUES(`dashboard_id`),
  `analyze_id` = VALUES(`analyze_id`),
  `widget_title` = VALUES(`widget_title`),
  `x` = VALUES(`x`),
  `y` = VALUES(`y`),
  `w` = VALUES(`w`),
  `h` = VALUES(`h`),
  `chart_type` = VALUES(`chart_type`),
  `refresh_interval` = VALUES(`refresh_interval`),
  `widget_config` = VALUES(`widget_config`),
  `updated_by` = VALUES(`updated_by`),
  `update_time` = NOW(),
  `is_deleted` = 0;
